export const SHOW_NOTES = 'SHOW_NOTES'
export const SELECT_NOTE = 'SELECT_NOTE'
export const ADD_NOTE = 'ADD_NOTE'
export const UPDATE_NOTE = 'UPDATE_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const FILTER_BY_TITLE = 'FILTER_BY_TITLE'
